//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreraSearch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public System.DateTime modified { get; set; }
        public string Title { get; set; }
        public string Authors { get; set; }
        public Nullable<decimal> Series { get; set; }
        public string Ids { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public string Publisher { get; set; }
        public string Languages { get; set; }
        public string Tags { get; set; }
        public string Formats { get; set; }
        public string Path { get; set; }
    }
}
